# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('score', models.FloatField(default=10.0)),
                ('category', models.CharField(choices=[('Book', '\u4e66\u7c4d'), ('Video', '\u5f71\u97f3'), ('Dress', '\u670d\u88c5'), ('Grocery', '\u98df\u54c1'), ('Computers', '\u7535\u5b50\u4ea7\u54c1')], max_length=10)),
            ],
        ),
    ]
