# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160412_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('read_product', 'can read product'),)},
        ),
    ]
