# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20160419_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.CharField(default='', max_length=30),
        ),
    ]
