# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_img', models.ImageField(upload_to='personinfo/imgs/')),
                ('sex', models.CharField(choices=[('B', '\u7537'), ('G', '\u5973')], max_length=1)),
                ('love', models.CharField(choices=[('YY', '\u97f3\u4e50'), ('YD', '\u8fd0\u52a8'), ('YX', '\u6e38\u620f')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
