# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo', '0002_remove_personinfo_head_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='head_img',
            field=models.ImageField(default='', upload_to='personinfo/imgs/'),
        ),
    ]
