# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 11:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.img_function


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo', '0003_personinfo_head_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='head_img',
            field=models.ImageField(default='', upload_to=utils.img_function.UploadToPathAndRename('personinfo/imgs/')),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
