# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo', '0004_auto_20160412_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
