# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo', '0005_auto_20160413_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='auth_mail',
            field=models.BooleanField(default=False),
        ),
    ]
