# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personinfo', '0006_personinfo_auth_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='love',
            field=models.CharField(choices=[('YY', '\u97f3\u4e50'), ('YD', '\u8fd0\u52a8'), ('YX', '\u6e38\u620f')], default='YY', max_length=2),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='sex',
            field=models.CharField(choices=[('B', '\u7537'), ('G', '\u5973')], default='B', max_length=1),
        ),
    ]
