# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import utils.img_function


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgage', models.ImageField(upload_to=utils.img_function.UploadToPathAndRename('product/imgs/'))),
                ('description', models.TextField(max_length=200)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
